feat: Add block proB pod unless authpolicy present
StatCan/gatekeeper-policies pull request #16
Opened 2021-06-09 13:55 UTC by wg102

Closes https://github.com/StatCan/gatekeeper-policies/issues/15

Assumptions:
The pod inherits the `notebook-name` and classification labels.

The authorization policy is `{NOTEBOOK_NAME}-rstudio-prob-block`

This blocks all the pods that are not unclassified. Not only the protected-b ones.
And it applies to all notebooks, it is not restricted to rstudio images since it is hard to detect which image it is.
The Authorization Policy will only be blocking certain URLs which are specific to rstudio.

cc @zachomedia

2021-07-14 12:38 UTC, wg102 commented
Updated the PR to be specifically about protected-b classification label since 

> If the classification label is not provided, then the workload is assumed to be Unclassified.

2021-07-21 14:09 UTC, zachomedia requested changes
Thank you, at first glance this is looking good to me! I just have one change to request that isn't anything major!

2021-07-21 14:09 UTC, zachomedia commented on aaw/prob-auth/template.yaml
> +          input.review.object.metadata.labels["data.statcan.gc.ca/classification"] == "protected-b"
I think we can remove this from the check here and apply a selector to the constraint object. See https://github.com/StatCan/gatekeeper-policies/blob/feat-aaw-policies/aaw/metadata-restrictions/constraint.yaml#L29-L34 as an example of this.

2021-08-16 15:13 UTC, blairdrummond approved these changes
LGTM!

2021-08-17 23:16 UTC, blairdrummond commented
@zachomedia Are you able to re-review?

2021-08-18 21:08 UTC, sylus commented
I rebased this and pushed to master :D 

https://github.com/StatCan/gatekeeper-policies/commit/fb765123e5bbc2bd4e26811b6615c051d38fa9e9

2021-08-18 21:08 UTC, closed without merging