Feat Internal User Policy
StatCan/gatekeeper-policies pull request #27
Opened 2022-03-16 22:37 UTC by saffaalvi

Resolves https://github.com/StatCan/daaas/issues/922

2022-03-17 00:13 UTC, sylus commented
This looks really good @saffaalvi just two minor nits.

- Can we have a new line after markdown heading
- Can the main README.md be updated

@zachomedia can you review as well?

2022-03-17 00:59 UTC, blairdrummond commented
@saffaalvi We should make the folder name the same as the policy name, just for clarity

Also one thing I'd like to check: The subject of a rolebinding or auth policy is assumed to be an email address here, but that may not be the case. I.e. this will deny (in some circumstances) ALL role bindings.

Let's add a quick line to the rego to check "is the subject an email address" before creating a violation

2022-03-17 11:37 UTC, blairdrummond requested changes
Small changes to the array indexes and email checking

2022-03-17 11:37 UTC, blairdrummond commented on general/internal-user/template.yaml
> +          email := obj.subjects[0].name
You can replace "0" with "_" to apply over the whole array, which is better

2022-03-17 11:37 UTC, blairdrummond commented on general/internal-user/template.yaml
> +          not isEmployee(email)
As mentioned in the other comment

internal = isEmail && not isEmployee

We just need to add the isEmail logic here

2022-03-17 11:37 UTC, blairdrummond commented on general/internal-user/template.yaml
> +          email := obj.spec.rules[0]["when"][0]["values"][0]
I would use _ instead of 0 to range over all rules

2022-03-21 15:22 UTC, saffaalvi commented
@sylus I'll be working on this today so will try my best to have them done by EOD!

2022-03-21 19:36 UTC, blairdrummond approved these changes
LGTM!

2022-03-22 00:02 UTC, sylus commented
This looks great @saffaalvi :D Awesome work!

2022-03-22 00:02 UTC, merged